#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_vmm="0.0.1"
  jq -n --arg vmm "$ver_vmm" '{vmm: $vmm}'
}

version "$@"
